# Generated by Django 5.2.4 on 2025-07-28 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hotelvendor_business_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoteluser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hotelvendor',
            options={},
        ),
        migrations.AlterModelTable(
            name='hoteluser',
            table='hotel.user',
        ),
        migrations.AlterModelTable(
            name='hotelvendor',
            table='hotel.vendor',
        ),
    ]
