# Generated by Django 5.2.4 on 2025-07-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_hoteluser_options_alter_hotelvendor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='hotel',
        ),
    ]
