# Generated by Django 5.2.4 on 2025-07-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_hotel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table=None,
        ),
    ]
